name: Docker CI/CD to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t myapp .

    - name: Tag Image
      run: |
        docker tag myapp:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/myapp:latest

    - name: Push to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/myapp:latest

    - name: Deploy via Bastion
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/awskey.pem
        chmod 600 ~/.ssh/awskey.pem

        ssh -o StrictHostKeyChecking=no -i ~/.ssh/awskey.pem ubuntu@${{ secrets.BASTION_HOST }} << 'EOF'

        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRIVATE_IP }} << 'INNER'

        bash /home/ubuntu/deploy.sh

        INNER
        EOF