name: Full CI/CD Pipeline (Frontend + Backend)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  BACKEND_REPO: backend
  FRONTEND_REPO: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Configure AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 3️⃣ Create ECR repos if not exist
    - name: Create ECR repositories
      run: |
        aws ecr describe-repositories --repository-names $BACKEND_REPO --region $AWS_REGION || \
        aws ecr create-repository --repository-name $BACKEND_REPO --region $AWS_REGION
        aws ecr describe-repositories --repository-names $FRONTEND_REPO --region $AWS_REGION || \
        aws ecr create-repository --repository-name $FRONTEND_REPO --region $AWS_REGION
    # 4️⃣ Login to ECR
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
    # 5️⃣ Build Backend
    - name: Build Backend Image
      run: |
        docker build -t backend ./backend
    # 6️⃣ Build Frontend
    - name: Build Frontend Image
      run: |
        docker build -t frontend ./frontend
    # 7️⃣ Tag Backend
    - name: Tag Backend
      run: |
        docker tag backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/backend:latest
    # 8️⃣ Tag Frontend
    - name: Tag Frontend
      run: |
        docker tag frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest
    # 9️⃣ Push Backend
    - name: Push Backend
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/backend:latest
    # 🔟 Push Frontend
    - name: Push Frontend
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest